#!/bin/bash

timeout=35

check() {
  echo checking $1;
  if easycrypt -I . -timeout $timeout $1 2>/dev/null;
  then echo passed: $1;
       echo "";
  else echo failed: $1;
       echo "";
       echo "skipping remaining scripts";
  exit 1;
  fi;
}

# list of files to check
check RandomFacts.ec
check GuessGame.ec
check FiniteApproximation.ec
check Averaging.ec
check JensensInf.ec
check JensensSquare.ec
check SquareConvex.ec
check Reflection.ec
check ReflectionComp.ec
check RewBasics.ec
check RewTrivial.ec
check RewTransformations.ec
check RewCommutes.ec
check RewCommutesSimple.ec
check RewMultRule.ec
check RewSumBindingAux.ec
check RewSumBindingGeneric.ec
check RewSumBindingCommitment.ec
check RewWithInit.ec
check RewWithInitAlt.ec
check CoinToss.ec


echo "DONE";
